ARG ARCH={{ arch }}
ARG NIM_VERSION
FROM elijahru/distcc-cross-compiler-client-{{ distro_slug }}:latest

# Allow compiling both locally and via distcc
ENV DISTCC_FALLBACK=1

# Install deps and clear pacman cache
RUN \
    pacman -Syu --noconfirm git && \
    (pacman -Sc --noconfirm || true)

# Install nim
ENV NIM_CI_VERSION=github-workflows
ADD https://raw.githubusercontent.com/elijahr/nim-ci/github-workflows/nim-ci.sh /scripts/
RUN /bin/bash -c "source /scripts/nim-ci.sh"

COPY /scripts/test.sh /scripts/test.sh
RUN chmod +x /scripts/test.sh
