FROM elijahru/distcc-cross-compiler-client-{{ distro|slugify }}:v0.3.3-{{ arch }}

# Allow compiling both locally and via distcc
ENV DISTCC_FALLBACK=1

ARG NIM_VERSION={{ nim_version }}
ENV NIM_VERSION={{ nim_version }}

# Install deps and clear pacman cache
RUN \
    pacman -Syu --noconfirm git && \
    (pacman -Sc --noconfirm || true)

# Install nim
ENV NIM_CI_VERSION=github-workflows
ADD https://raw.githubusercontent.com/elijahr/nim-ci/github-workflows/nim-ci.sh /scripts/
RUN /bin/bash -c "source /scripts/nim-ci.sh"

# TODO - cleanup!

COPY /scripts/test.sh /scripts/test.sh
RUN chmod +x /scripts/test.sh && /scripts/test.sh {{ nim_version }} {{ arch }}
