FROM elijahru/distcc-cross-compiler-client-{{ distro|slugify }}:v0.5.1-{{ arch }}

# Allow compiling both locally and via distcc
ENV DISTCC_FALLBACK=1

ARG NIM_VERSION={{ nim_version }}
ARG PATH=/root/.active-nim/bin:/root/.nimble/bin:/root/.choosenim/bin:/usr/lib/ccache/bin:/usr/lib/distcc/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
ENV NIM_VERSION={{ nim_version }}
ENV PATH=/root/.active-nim/bin:/root/.nimble/bin:/root/.choosenim/bin:/usr/lib/ccache/bin:/usr/lib/distcc/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

# Install deps and clear pacman cache
RUN \
    pacman -Syu --noconfirm git && \
    (pacman -Sc --noconfirm || true)

# Install nim
ENV NIM_CI_VERSION=github-workflows
ADD https://raw.githubusercontent.com/elijahr/nim-ci/github-workflows/nim-ci.sh /scripts/
RUN \
    /bin/bash -c "source /scripts/nim-ci.sh && rm -Rf /scripts/nim-ci.sh" && \
    /bin/bash -c "test \$(nim -v | head -n 1 | awk '{ print \$4 }') == {{ nim_version }}"
