ARG ARCH={{ arch }}
ARG NIM_VERSION
FROM elijahru/distcc-cross-compiler-client-{{ distro|slugify }}:latest

# Allow compiling both locally and via distcc
ENV DISTCC_FALLBACK=1

ENV NIM_VERSION=$NIM_VERSION

RUN apt-get update; \
  apt-get install -y \
    git curl; \
  apt-get clean

# Install Nim
ENV NIM_CI_VERSION=github-workflows
ADD https://raw.githubusercontent.com/elijahr/nim-ci/github-workflows/nim-ci.sh /scripts/
RUN /bin/bash -c "source /scripts/nim-ci.sh"

ENV PATH=/root/.active-nim/bin:/root/.nimble/bin:/root/.choosenim/bin:/usr/lib/ccache:/usr/lib/distcc:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# TODO - cleanup!

COPY /scripts/test.sh /scripts/test.sh
RUN chmod +x /scripts/test.sh && /scripts/test.sh
