
FROM elijahru/distcc-cross-compiler-client-{{ distro|slugify }}:v0.5.1-{{ arch }}

# Allow compiling both locally and via distcc
ENV DISTCC_FALLBACK=1

ARG NIM_VERSION={{ nim_version }}
ARG PATH=/root/.active-nim/bin:/root/.nimble/bin:/root/.choosenim/bin:/usr/lib/ccache:/usr/lib/distcc:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV NIM_VERSION={{ nim_version }}
ENV PATH=/root/.active-nim/bin:/root/.nimble/bin:/root/.choosenim/bin:/usr/lib/ccache:/usr/lib/distcc:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN apt-get update; \
  apt-get install -y \
    git curl; \
  apt-get clean

# Install Nim
ENV NIM_CI_VERSION=github-workflows
ADD https://raw.githubusercontent.com/elijahr/nim-ci/github-workflows/nim-ci.sh /scripts/
RUN \
    /bin/bash -c "source /scripts/nim-ci.sh && rm -Rf /scripts" && \
    /bin/bash -c 'test $(nim -v | head -n 1 | awk \\\'{ print $4 }\\\') == {{ nim_version }}'
